
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(Module) {
  Module = Module || {};

var a;a||(a=typeof Module !== 'undefined' ? Module : {});var f={},g;for(g in a)a.hasOwnProperty(g)&&(f[g]=a[g]);a.arguments=[];a.thisProgram="./this.program";a.quit=function(b,c){throw c;};a.preRun=[];a.postRun=[];var h=!1,k=!1,l=!1,m=!1;h="object"===typeof window;k="function"===typeof importScripts;l="object"===typeof process&&"function"===typeof require&&!h&&!k;m=!h&&!l&&!k;var n="";
if(l){n=__dirname+"/";var p,q;a.read=function(b,c){p||(p=require("fs"));q||(q=require("path"));b=q.normalize(b);b=p.readFileSync(b);return c?b:b.toString()};a.readBinary=function(b){b=a.read(b,!0);b.buffer||(b=new Uint8Array(b));b.buffer||r("Assertion failed: undefined");return b};1<process.argv.length&&(a.thisProgram=process.argv[1].replace(/\\/g,"/"));a.arguments=process.argv.slice(2);process.on("uncaughtException",function(b){if(!(b instanceof t))throw b;});process.on("unhandledRejection",r);a.quit=
function(b){process.exit(b)};a.inspect=function(){return"[Emscripten Module object]"}}else if(m)"undefined"!=typeof read&&(a.read=function(b){return read(b)}),a.readBinary=function(b){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(b));b=read(b,"binary");"object"===typeof b||r("Assertion failed: undefined");return b},"undefined"!=typeof scriptArgs?a.arguments=scriptArgs:"undefined"!=typeof arguments&&(a.arguments=arguments),"function"===typeof quit&&(a.quit=function(b){quit(b)});
else if(h||k)k?n=self.location.href:document.currentScript&&(n=document.currentScript.src),_scriptDir&&(n=_scriptDir),0!==n.indexOf("blob:")?n=n.substr(0,n.lastIndexOf("/")+1):n="",a.read=function(b){var c=new XMLHttpRequest;c.open("GET",b,!1);c.send(null);return c.responseText},k&&(a.readBinary=function(b){var c=new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),a.readAsync=function(b,c,e){var d=new XMLHttpRequest;d.open("GET",b,!0);
d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?c(d.response):e()};d.onerror=e;d.send(null)},a.setWindowTitle=function(b){document.title=b};var u=a.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),v=a.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||u);for(g in f)f.hasOwnProperty(g)&&(a[g]=f[g]);f=void 0;
var w={"f64-rem":function(b,c){return b%c},"debugger":function(){debugger}};"object"!==typeof WebAssembly&&v("no native wasm support detected");var y,z=!1;"undefined"!==typeof TextDecoder&&new TextDecoder("utf8");"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function A(b){0<b%65536&&(b+=65536-b%65536);return b}var buffer,B,C,D;
function E(){a.HEAP8=B=new Int8Array(buffer);a.HEAP16=new Int16Array(buffer);a.HEAP32=D=new Int32Array(buffer);a.HEAPU8=C=new Uint8Array(buffer);a.HEAPU16=new Uint16Array(buffer);a.HEAPU32=new Uint32Array(buffer);a.HEAPF32=new Float32Array(buffer);a.HEAPF64=new Float64Array(buffer)}var F=a.TOTAL_MEMORY||16777216;5242880>F&&v("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+F+"! (TOTAL_STACK=5242880)");
a.buffer?buffer=a.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(y=new WebAssembly.Memory({initial:F/65536}),buffer=y.buffer):buffer=new ArrayBuffer(F);E();D[21700]=5329936;function G(b){for(;0<b.length;){var c=b.shift();if("function"==typeof c)c();else{var e=c.H;"number"===typeof e?void 0===c.G?a.dynCall_v(e):a.dynCall_vi(e,c.G):e(void 0===c.G?null:c.G)}}}var H=[],I=[],J=[],K=[],L=!1;function M(){var b=a.preRun.shift();H.unshift(b)}var N=0,O=null,P=null;
a.preloadedImages={};a.preloadedAudios={};function Q(){var b=R;return String.prototype.startsWith?b.startsWith("data:application/octet-stream;base64,"):0===b.indexOf("data:application/octet-stream;base64,")}var R="harfbuzzjs.wasm";if(!Q()){var S=R;R=a.locateFile?a.locateFile(S,n):n+S}function T(){try{if(a.wasmBinary)return new Uint8Array(a.wasmBinary);if(a.readBinary)return a.readBinary(R);throw"both async and sync fetching of the wasm failed";}catch(b){r(b)}}
function U(){return a.wasmBinary||!h&&!k||"function"!==typeof fetch?new Promise(function(b){b(T())}):fetch(R,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+R+"'";return b.arrayBuffer()}).catch(function(){return T()})}
function V(b){function c(b){a.asm=b.exports;N--;a.monitorRunDependencies&&a.monitorRunDependencies(N);0==N&&(null!==O&&(clearInterval(O),O=null),P&&(b=P,P=null,b()))}function e(b){c(b.instance)}function d(b){U().then(function(b){return WebAssembly.instantiate(b,x)}).then(b,function(b){v("failed to asynchronously prepare wasm: "+b);r(b)})}var x={env:b,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:w};N++;a.monitorRunDependencies&&a.monitorRunDependencies(N);if(a.instantiateWasm)try{return a.instantiateWasm(x,
c)}catch(aa){return v("Module.instantiateWasm callback failed with error: "+aa),!1}a.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Q()||"function"!==typeof fetch?d(e):WebAssembly.instantiateStreaming(fetch(R,{credentials:"same-origin"}),x).then(e,function(b){v("wasm streaming compile failed: "+b);v("falling back to ArrayBuffer instantiation");d(e)});return{}}
a.asm=function(b,c){c.memory=y;c.table=new WebAssembly.Table({initial:226,maximum:226,element:"anyfunc"});c.__memory_base=1024;c.__table_base=0;return V(c)};function W(){return B.length}function X(b){a.___errno_location&&(D[a.___errno_location()>>2]=b);return b}
var Y=a.asm({},{b:r,k:function(){},c:X,j:function(){return 0},i:function(){},h:W,g:function(b,c,e){C.set(C.subarray(c,c+e),b)},f:function(b){if(2147418112<b)return!1;for(var c=Math.max(W(),16777216);c<b;)536870912>=c?c=A(2*c):c=Math.min(A((3*c+2147483648)/4),2147418112);b=A(c);var e=buffer.byteLength;try{var d=-1!==y.grow((b-e)/65536)?buffer=y.buffer:null}catch(x){d=null}if(!d||d.byteLength!=c)return!1;E();return!0},e:function(b){switch(b){case 30:return 16384;case 85:return 131068;case 132:case 133:case 12:case 137:case 138:case 15:case 235:case 16:case 17:case 18:case 19:case 20:case 149:case 13:case 10:case 236:case 153:case 9:case 21:case 22:case 159:case 154:case 14:case 77:case 78:case 139:case 80:case 81:case 82:case 68:case 67:case 164:case 11:case 29:case 47:case 48:case 95:case 52:case 51:case 46:return 200809;
case 79:return 0;case 27:case 246:case 127:case 128:case 23:case 24:case 160:case 161:case 181:case 182:case 242:case 183:case 184:case 243:case 244:case 245:case 165:case 178:case 179:case 49:case 50:case 168:case 169:case 175:case 170:case 171:case 172:case 97:case 76:case 32:case 173:case 35:return-1;case 176:case 177:case 7:case 155:case 8:case 157:case 125:case 126:case 92:case 93:case 129:case 130:case 131:case 94:case 91:return 1;case 74:case 60:case 69:case 70:case 4:return 1024;case 31:case 42:case 72:return 32;
case 87:case 26:case 33:return 2147483647;case 34:case 1:return 47839;case 38:case 36:return 99;case 43:case 37:return 2048;case 0:return 2097152;case 3:return 65536;case 28:return 32768;case 44:return 32767;case 75:return 16384;case 39:return 1E3;case 89:return 700;case 71:return 256;case 40:return 255;case 2:return 100;case 180:return 64;case 25:return 20;case 5:return 16;case 6:return 6;case 73:return 4;case 84:return"object"===typeof navigator?navigator.hardwareConcurrency||1:1}X(22);return-1},
d:function(){r("OOM")},a:86800},buffer);a.asm=Y;a._free=function(){return a.asm.l.apply(null,arguments)};a._hb_blob_create=function(){return a.asm.m.apply(null,arguments)};a._hb_blob_destroy=function(){return a.asm.n.apply(null,arguments)};a._hb_blob_get_length=function(){return a.asm.o.apply(null,arguments)};a._hb_buffer_add_utf8=function(){return a.asm.p.apply(null,arguments)};a._hb_buffer_create=function(){return a.asm.q.apply(null,arguments)};
a._hb_buffer_destroy=function(){return a.asm.r.apply(null,arguments)};a._hb_buffer_get_length=function(){return a.asm.s.apply(null,arguments)};a._hb_buffer_guess_segment_properties=function(){return a.asm.t.apply(null,arguments)};a._hb_buffer_serialize_glyphs=function(){return a.asm.u.apply(null,arguments)};a._hb_buffer_set_direction=function(){return a.asm.v.apply(null,arguments)};a._hb_direction_from_string=function(){return a.asm.w.apply(null,arguments)};
a._hb_face_create=function(){return a.asm.x.apply(null,arguments)};a._hb_face_destroy=function(){return a.asm.y.apply(null,arguments)};a._hb_font_create=function(){return a.asm.z.apply(null,arguments)};a._hb_font_destroy=function(){return a.asm.A.apply(null,arguments)};a._hb_font_set_scale=function(){return a.asm.B.apply(null,arguments)};a._hb_shape=function(){return a.asm.C.apply(null,arguments)};a._hb_version_string=function(){return a.asm.D.apply(null,arguments)};
a._malloc=function(){return a.asm.E.apply(null,arguments)};a.dynCall_vi=function(){return a.asm.F.apply(null,arguments)};a.asm=Y;a.then=function(b){if(a.calledRun)b(a);else{var c=a.onRuntimeInitialized;a.onRuntimeInitialized=function(){c&&c();b(a)}}return a};function t(b){this.name="ExitStatus";this.message="Program terminated with exit("+b+")";this.status=b}t.prototype=Error();t.prototype.constructor=t;P=function ba(){a.calledRun||Z();a.calledRun||(P=ba)};
function Z(){function b(){if(!a.calledRun&&(a.calledRun=!0,!z)){L||(L=!0,G(I));G(J);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var b=a.postRun.shift();K.unshift(b)}G(K)}}if(!(0<N)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)M();G(H);0<N||a.calledRun||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):
b())}}a.run=Z;function r(b){if(a.onAbort)a.onAbort(b);void 0!==b?(u(b),v(b),b=JSON.stringify(b)):b="";z=!0;throw"abort("+b+"). Build with -s ASSERTIONS=1 for more info.";}a.abort=r;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();a.noExitRuntime=!0;Z();


  return Module
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = Module;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return Module; });
    else if (typeof exports === 'object')
      exports["Module"] = Module;
    